name: "\U0001F38A Feature request"
description: "Suggest adding a feature that is not yet in ExaGO."
#title: "Bug: "
labels: [enhancement]
body:
  # CHECKBOX:
  - type: checkboxes
    id: issue_relates_to
    attributes:
      label: "Issue applies to:"
      description: You may select more than one.
      options:
        - label: PFLOW
        - label: OPFLOW
        - label: TCOPFLOW
        - label: SCOPFLOW
        - label: SOPFLOW
        - label: CMake and build system
        - label: Spack
        - label: Visualization
        - label: Documentation
        - label: Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Please add a concise summary of your suggestion here."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Rationale"
      description: "Is your feature request related to a problem? Please describe it!."
    validations:
      required: true

  - type: input
    id: exago_version
    attributes:
      label: "ExaGO version"
      description: |
        Please include the relevantversion of ExaGO™.
        If building from source on a non-tagged version, please include the commit hash.
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: "System and environment details"
      description: |
        Is your feature system specific? If so, please include relevant details, such as:
        - Operating system  
        - Compilers  
        - Hardware backends (CUDA, HIP)  
        - Dependencies and package versions  
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed solution"
      description: "Describe your proposed feature and highlight implementation details, when applicable."

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional information"
      description: "Add any relevant references or examples."
